"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { FileAudio, FileVideo, LoaderCircle, UploadCloud, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { inspectLocalMedia } from "@/features/intake/media-inspection";
import { supportedMediaFormats, type MediaInspection, type MediaMetadata } from "@/shared/contracts/media";

function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function formatDuration(seconds: number) { const minutes = Math.floor(seconds / 60); const remainder = Math.round(seconds % 60).toString().padStart(2, "0"); return `${minutes}:${remainder}`; }

export function IntakePanel() {
  const inputRef = useRef<HTMLInputElement>(null); const [inspection, setInspection] = useState<MediaInspection>(); const [selectedFile, setSelectedFile] = useState<File>();
  async function selectFile(file?: File) { if (!file) return; setSelectedFile(file); setInspection(undefined); const result = await inspectLocalMedia(file); setInspection(result); }
  function remove() { setSelectedFile(undefined); setInspection(undefined); if (inputRef.current) inputRef.current.value = ""; }
  if (inspection?.status === "ready") return <ReadyCard metadata={inspection.metadata} onRemove={remove} onReplace={() => inputRef.current?.click()} inputRef={inputRef} onSelect={selectFile} />;
  if (inspection?.status === "error") return <ErrorCard inspection={inspection} onRemove={remove} onReplace={() => inputRef.current?.click()} inputRef={inputRef} onSelect={selectFile} />;
  if (selectedFile) return <div className="mt-10 rounded-[20px] border border-[var(--border)] bg-[var(--surface-raised)] p-8" role="status"><div className="flex items-center gap-3"><LoaderCircle className="size-5 animate-spin text-[var(--primary)]" aria-hidden="true" /><div><p className="font-medium">Inspecting file…</p><p className="mt-1 text-sm text-[var(--muted-foreground)]">Reading local metadata. Nothing is uploaded and no processing job has started.</p></div></div></div>;
  return <div className="mt-10 rounded-[20px] border border-dashed border-[var(--border)] bg-[var(--surface-raised)] p-8 text-center"><input ref={inputRef} type="file" accept={supportedMediaFormats.map((format) => `.${format}`).join(",")} className="sr-only" onChange={(event) => void selectFile(event.target.files?.[0])} /><div role="button" tabIndex={0} aria-label="Choose a local audio or video file" onClick={() => inputRef.current?.click()} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); inputRef.current?.click(); } }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void selectFile(event.dataTransfer.files?.[0]); }} className="mx-auto flex min-h-[300px] max-w-2xl flex-col items-center justify-center rounded-[var(--radius-lg)] px-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"><span className="grid size-14 place-items-center rounded-2xl bg-[var(--surface-elevated)] text-[var(--primary)]"><UploadCloud className="size-7" aria-hidden="true" /></span><h2 className="mt-6 text-xl font-semibold tracking-[-0.02em]">Choose a local recording</h2><p className="mt-3 max-w-md text-sm leading-6 text-[var(--muted-foreground)]">Drop audio or video here, or use Browse files. Your media stays on this device.</p><Button type="button" className="mt-6" onClick={(event) => { event.stopPropagation(); inputRef.current?.click(); }}>Browse files</Button><p className="mt-5 text-xs text-[var(--muted-foreground)]">Supported: {supportedMediaFormats.map((format) => format.toUpperCase()).join(", ")}</p></div></div>;
}

function MediaInput({ inputRef, onSelect }: { inputRef: React.RefObject<HTMLInputElement | null>; onSelect: (file?: File) => void }) { return <input ref={inputRef} type="file" accept={supportedMediaFormats.map((format) => `.${format}`).join(",")} className="sr-only" onChange={(event) => void onSelect(event.target.files?.[0])} />; }
function ReadyCard({ metadata, onRemove, onReplace, inputRef, onSelect }: { metadata: MediaMetadata; onRemove: () => void; onReplace: () => void; inputRef: React.RefObject<HTMLInputElement | null>; onSelect: (file?: File) => void }) { const Icon = metadata.mediaKind === "video" ? FileVideo : FileAudio; return <section className="mt-10 rounded-[var(--radius-lg)] border border-[color-mix(in_srgb,var(--primary)_35%,transparent)] bg-[var(--surface-raised)] p-5" aria-labelledby="media-ready-title"><MediaInput inputRef={inputRef} onSelect={onSelect} /><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-[var(--radius-md)] bg-[var(--surface-elevated)] text-[var(--primary)]"><Icon className="size-5" aria-hidden="true" /></span><div><h2 id="media-ready-title" className="font-semibold">Ready to enhance</h2><p className="mt-1 break-all text-sm text-[var(--foreground)]">{metadata.sourceName}</p></div></div><Badge>Local source</Badge></div><dl className="mt-6 grid gap-4 border-t border-[var(--border)] pt-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-[var(--muted-foreground)]">Media type</dt><dd className="mt-1 text-sm font-medium">{metadata.mediaKind === "video" ? "Video with audio" : "Audio"}</dd></div><div><dt className="text-xs text-[var(--muted-foreground)]">Duration</dt><dd className="mt-1 text-sm font-medium">{formatDuration(metadata.durationSeconds)}</dd></div><div><dt className="text-xs text-[var(--muted-foreground)]">File size</dt><dd className="mt-1 text-sm font-medium">{formatBytes(metadata.sizeBytes)}</dd></div><div><dt className="text-xs text-[var(--muted-foreground)]">Audio stream</dt><dd className="mt-1 text-sm font-medium">{metadata.audioStream.summary}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3"><Button type="button" onClick={() => undefined} disabled>Continue to editor</Button><Button type="button" variant="outline" onClick={onReplace}>Replace file</Button><Button type="button" variant="ghost" onClick={onRemove}>Remove</Button></div></section>; }
function ErrorCard({ inspection, onRemove, onReplace, inputRef, onSelect }: { inspection: Extract<MediaInspection, { status: "error" }>; onRemove: () => void; onReplace: () => void; inputRef: React.RefObject<HTMLInputElement | null>; onSelect: (file?: File) => void }) { return <section className="mt-10 rounded-[var(--radius-lg)] border border-rose-300/30 bg-[var(--surface-raised)] p-5" role="alert" aria-labelledby="media-error-title"><MediaInput inputRef={inputRef} onSelect={onSelect} /><div className="flex items-start gap-3"><X className="mt-0.5 size-5 shrink-0 text-rose-300" aria-hidden="true" /><div><h2 id="media-error-title" className="font-semibold">Couldn’t inspect this file</h2><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{inspection.message}</p>{inspection.code === "UNSUPPORTED_MEDIA" && <p className="mt-3 text-xs text-[var(--muted-foreground)]">Supported: {supportedMediaFormats.map((format) => format.toUpperCase()).join(", ")}</p>}{inspection.code === "INSPECTION_UNAVAILABLE" && <p className="mt-3 text-sm"><Link className="text-[var(--primary)] underline" href="/settings#diagnostics">Open local diagnostics</Link></p>}</div></div><div className="mt-6 flex flex-wrap gap-3"><Button type="button" onClick={onReplace}>Replace file</Button><Button type="button" variant="outline" onClick={onRemove}>Remove</Button></div></section>; }
