"use client";

import { useState } from "react";
import { Check, ChevronDown, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useSettings } from "@/components/settings-context";
import { clearLocalGeneratedData, getLocalStorage } from "@/components/settings-storage";
import type { AppSettings } from "@/shared/contracts/settings";

function Group({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { const id = `${title.replaceAll(" ", "-").toLowerCase()}-heading`; return <section className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-raised)] p-5" aria-labelledby={id}><div className="mb-5"><h2 id={id} className="text-base font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-[var(--muted-foreground)]">{description}</p></div><div className="divide-y divide-[var(--border)]">{children}</div></section>; }
function Row({ label, description, children }: { label: string; description: string; children: React.ReactNode }) { return <div className="flex min-h-16 flex-col gap-3 py-4 first:pt-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0 sm:max-w-[62%]"><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs leading-5 text-[var(--muted-foreground)]">{description}</p></div><div className="shrink-0">{children}</div></div>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { return <label className="relative block"><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 min-w-40 appearance-none rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-elevated)] px-3 pr-9 text-sm text-[var(--foreground)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 size-4 text-[var(--muted-foreground)]" aria-hidden="true" /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <button type="button" role="switch" aria-label={label} aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-7 w-12 rounded-full border transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] ${checked ? "border-[var(--primary)] bg-[var(--primary)]" : "border-[var(--border)] bg-[var(--surface-elevated)]"}`}><span className={`absolute top-1 size-5 rounded-full bg-white shadow-sm transition-transform ${checked ? "translate-x-6" : "translate-x-1"}`} /></button>; }

export function SettingsPanel() {
  const { settings, updateSettings } = useSettings(); const [cleanup, setCleanup] = useState<"previews" | "outputs" | "history" | "all" | null>(null); const [message, setMessage] = useState("");
  const set = (group: "appearance" | "playback" | "output" | "accessibility", key: string, value: string | boolean) => { const current = settings[group] as Record<string, string | boolean>; updateSettings({ ...settings, [group]: { ...current, [key]: value } } as AppSettings); };
  const confirmCleanup = () => { if (!cleanup) return; clearLocalGeneratedData(getLocalStorage(), cleanup); setMessage(`${cleanup === "all" ? "Generated previews, outputs, and history metadata" : cleanup} cleared locally.`); setCleanup(null); };
  return <div className="mt-10 grid gap-5 xl:grid-cols-2">
    <Group title="Appearance" description="Shape the workspace to fit your eyes and environment."><Row label="Theme" description="Use your device preference, or choose a fixed theme."><Select label="Theme" value={settings.appearance.theme} options={[{ value: "system", label: "System" }, { value: "dark", label: "Dark" }, { value: "light", label: "Light" }]} onChange={(value) => set("appearance", "theme", value)} /></Row><Row label="Workspace density" description="Choose more breathing room or a compact layout."><Select label="Workspace density" value={settings.appearance.density} options={[{ value: "comfortable", label: "Comfortable" }, { value: "compact", label: "Compact" }]} onChange={(value) => set("appearance", "density", value)} /></Row><Row label="Reduced motion" description="Replace animated transitions with calm, static state changes."><Toggle label="Reduced motion" checked={settings.appearance.reducedMotion} onChange={(value) => set("appearance", "reducedMotion", value)} /></Row><Row label="Waveform contrast" description="Increase waveform distinction without relying on color alone."><Select label="Waveform contrast" value={settings.appearance.waveformContrast} options={[{ value: "standard", label: "Standard" }, { value: "high", label: "High contrast" }]} onChange={(value) => set("appearance", "waveformContrast", value)} /></Row></Group>
    <Group title="Playback" description="Make previews predictable and easy to control."><Row label="Seek interval" description="How far keyboard and transport seek buttons move."><Select label="Seek interval" value={settings.playback.seekInterval} options={["5", "10", "15", "30"].map((value) => ({ value, label: `${value} seconds` }))} onChange={(value) => set("playback", "seekInterval", value)} /></Row><Row label="Autoplay preview" description="Previews remain paused by default to avoid unexpected sound."><Toggle label="Autoplay preview" checked={settings.playback.autoplayPreview} onChange={(value) => set("playback", "autoplayPreview", value)} /></Row><Row label="Keyboard shortcuts" description="Enable Space, arrow keys, and editor shortcut commands."><Toggle label="Keyboard shortcuts" checked={settings.playback.keyboardShortcuts} onChange={(value) => set("playback", "keyboardShortcuts", value)} /></Row></Group>
    <Group title="Output" description="Set safe defaults for future enhancement jobs."><Row label="Default format" description="Audio uses 48 kHz WAV PCM 24-bit. Video preserves its container when supported."><Select label="Default format" value={settings.output.format} options={[{ value: "audio-wav", label: "Audio · WAV PCM 24-bit" }, { value: "source-video", label: "Video · source container" }, { value: "mp4", label: "Video · MP4 fallback" }]} onChange={(value) => set("output", "format", value)} /></Row><Row label="Quality" description="High keeps more detail; standard uses a smaller output when supported."><Select label="Quality" value={settings.output.quality} options={[{ value: "high", label: "High" }, { value: "standard", label: "Standard" }]} onChange={(value) => set("output", "quality", value)} /></Row><Row label="Destination" description="Choose a local destination when the browser supports it, otherwise save through the browser."><Select label="Destination" value={settings.output.destination} options={[{ value: "ask", label: "Ask each time" }, { value: "browser", label: "Browser downloads" }]} onChange={(value) => set("output", "destination", value)} /></Row><Row label="Overwrite confirmation" description="Existing files always receive an explicit warning before replacement."><Select label="Overwrite confirmation" value={settings.output.overwriteConfirmation} options={[{ value: "always", label: "Always confirm" }, { value: "ask", label: "Ask when needed" }]} onChange={(value) => set("output", "overwriteConfirmation", value)} /></Row></Group>
    <Group title="Accessibility" description="Keep controls, announcements, and focus behavior clear."><Row label="Announcements" description="Choose how much job and surface state is announced."><Select label="Announcements" value={settings.accessibility.announcements} options={[{ value: "minimal", label: "Minimal" }, { value: "standard", label: "Standard" }, { value: "verbose", label: "Verbose" }]} onChange={(value) => set("accessibility", "announcements", value)} /></Row><Row label="Focus after dialogs" description="Return focus to the triggering control, or move it to the main surface."><Select label="Focus after dialogs" value={settings.accessibility.focusBehavior} options={[{ value: "restore", label: "Restore focus" }, { value: "main", label: "Move to main content" }]} onChange={(value) => set("accessibility", "focusBehavior", value)} /></Row></Group>
    <Group title="Privacy and cleanup" description="Processing stays on this device. Originals are never included in generated-file cleanup."><Row label="Preview retention" description="Previews older than seven days are eligible for automatic cleanup; final outputs remain until removed."><div className="flex gap-2"><Badge>7-day cleanup</Badge><Button variant="outline" size="sm" onClick={() => setCleanup("previews")}><Trash2 className="size-4" aria-hidden="true" /> Clear previews</Button></div></Row><Row label="Generated files" description="Remove derived previews and outputs only after reviewing the exact scope."><Button variant="outline" size="sm" onClick={() => setCleanup("outputs")}><Trash2 className="size-4" aria-hidden="true" /> Clear generated outputs</Button></Row><Row label="History metadata" description="History remains until you clear it; original media is never touched."><Button variant="outline" size="sm" onClick={() => setCleanup("history")}><Trash2 className="size-4" aria-hidden="true" /> Clear history</Button></Row><Row label="All eligible generated data" description="Clear previews, generated outputs, and history metadata together."><Button variant="outline" size="sm" onClick={() => setCleanup("all")}><Trash2 className="size-4" aria-hidden="true" /> Clear all</Button></Row></Group>
    <div className="xl:col-span-2" aria-live="polite">{message && <p className="rounded-[var(--radius-md)] border border-[color-mix(in_srgb,var(--primary)_35%,transparent)] bg-[color-mix(in_srgb,var(--primary)_8%,transparent)] p-3 text-sm text-[var(--primary)]">{message}</p>}</div>
    {cleanup && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div role="dialog" aria-modal="true" aria-labelledby="cleanup-title" className="w-full max-w-md rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-raised)] p-6 shadow-2xl"><h2 id="cleanup-title" className="text-lg font-semibold">Confirm local cleanup</h2><p className="mt-3 text-sm leading-6 text-[var(--muted-foreground)]">This will clear <strong className="text-[var(--foreground)]">{cleanup === "all" ? "generated previews, outputs, and history metadata" : cleanup === "previews" ? "generated previews" : cleanup === "outputs" ? "generated outputs" : "history metadata"}</strong> from this device. Original media is not affected.</p><div className="mt-6 flex justify-end gap-3"><Button variant="ghost" onClick={() => setCleanup(null)}>Cancel</Button><Button onClick={confirmCleanup}>Confirm cleanup</Button></div></div></div>}
  </div>;
}
