"use client";

import { useMemo, useState } from "react";
import { RotateCcw, SlidersHorizontal } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { defaultProcessingProfile, defaultProcessingStages, normalizeProcessingProfile, type CapabilityState, type EffectId, type ProcessingProfile, type ProcessingStage } from "@/shared/contracts/processing";

const effectCopy: Record<EffectId, { title: string; description: string; parameter: "intensity" | "targetLufs"; unit: string }> = {
  "noise-removal": { title: "Noise removal", description: "Reduce steady background noise while protecting speech detail.", parameter: "intensity", unit: "% intensity" },
  "voice-clarity": { title: "Voice clarity", description: "Bring speech presence forward so words are easier to follow.", parameter: "intensity", unit: "% intensity" },
  "loudness-normalization": { title: "Loudness normalization", description: "Bring the overall speech level toward a consistent listening target.", parameter: "targetLufs", unit: "LUFS" },
  "echo-reverb-reduction": { title: "Echo/reverb reduction", description: "Soften room reflections that make speech sound distant or blurred.", parameter: "intensity", unit: "% reduction" },
};

const readyCapability: CapabilityState = { status: "ready", cpuSafe: true };

function valueFor(stage: ProcessingStage) { return stage.id === "loudness-normalization" ? stage.parameters.targetLufs : stage.parameters.intensity; }
function displayValue(stage: ProcessingStage) { return stage.id === "loudness-normalization" ? `${valueFor(stage)} LUFS` : `${valueFor(stage)}%`; }

export function EffectInspector({ mediaRef, selectedAudioStreamId, capabilities = {}, onProfileChange }: { mediaRef: string; selectedAudioStreamId?: string; capabilities?: Partial<Record<EffectId, CapabilityState>>; onProfileChange?: (profile: ProcessingProfile) => void }) {
  const [profile, setProfile] = useState(() => { const initial = defaultProcessingProfile(mediaRef, selectedAudioStreamId); return { ...initial, stages: initial.stages.map((stage) => capabilities[stage.id]?.status === "unavailable" ? { ...stage, enabled: false } : stage) }; });
  const update = (next: ProcessingProfile) => { const normalized = normalizeProcessingProfile(next); setProfile(normalized); onProfileChange?.(normalized); };
  const enabledStages = useMemo(() => profile.stages.filter((stage) => stage.enabled), [profile.stages]);
  function toggle(stage: ProcessingStage) { const capability = capabilities[stage.id] ?? readyCapability; if (!stage.enabled && capability.status === "unavailable") return; update({ ...profile, stages: profile.stages.map((candidate) => candidate.id === stage.id ? { ...candidate, enabled: !candidate.enabled } : candidate) }); }
  function changeValue(stage: ProcessingStage, rawValue: number) { const value = stage.id === "loudness-normalization" ? Math.max(-24, Math.min(-9, rawValue)) : Math.max(0, Math.min(100, rawValue)); update({ ...profile, stages: profile.stages.map((candidate) => candidate.id === stage.id ? { ...candidate, parameters: stage.id === "loudness-normalization" ? { targetLufs: value } : { intensity: value } } : candidate) } as ProcessingProfile); }
  function reset(stage: ProcessingStage) { update({ ...profile, stages: profile.stages.map((candidate) => candidate.id === stage.id ? defaultProcessingStages.find((fallback) => fallback.id === stage.id)! : candidate) }); }
  return <section className="mt-8 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-raised)] p-5" aria-labelledby="effects-title"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--primary)]">Speech profile</p><h2 id="effects-title" className="mt-1 text-xl font-semibold">Tune the enhancement stages</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted-foreground)]">Each stage stays independent, so you can decide exactly what will run on this local media.</p></div><Badge><SlidersHorizontal className="mr-1 size-3.5" aria-hidden="true" />Draft profile</Badge></div><div className="mt-6 space-y-3">{profile.stages.map((stage, index) => <EffectCard key={stage.id} stage={stage} index={index} capability={capabilities[stage.id] ?? readyCapability} onToggle={() => toggle(stage)} onChange={(value) => changeValue(stage, value)} onReset={() => reset(stage)} />)}</div><div className="mt-6 rounded-[var(--radius-md)] border border-[color-mix(in_srgb,var(--primary)_28%,transparent)] bg-[var(--surface-elevated)] p-4"><p className="text-sm font-medium">What will run</p><p className="mt-1 text-sm leading-6 text-[var(--muted-foreground)]">{enabledStages.length ? enabledStages.map((stage, index) => `${index + 1}. ${effectCopy[stage.id].title} (${displayValue(stage)})`).join(" · ") : "No enhancement stages selected. Your source remains unchanged."}</p></div></section>;
}

function EffectCard({ stage, index, capability, onToggle, onChange, onReset }: { stage: ProcessingStage; index: number; capability: CapabilityState; onToggle: () => void; onChange: (value: number) => void; onReset: () => void }) { const copy = effectCopy[stage.id]; const unavailable = capability.status === "unavailable"; const value = valueFor(stage); const inputId = `effect-${stage.id}`; return <article className={`rounded-[var(--radius-lg)] border p-4 transition-colors ${stage.enabled ? "border-[color-mix(in_srgb,var(--primary)_35%,transparent)] bg-[var(--surface)]" : "border-[var(--border)] bg-[var(--surface-elevated)] opacity-80"}`}><div className="flex items-start gap-3"><div className="mt-1 grid size-7 shrink-0 place-items-center rounded-full bg-[var(--surface-elevated)] text-xs font-semibold text-[var(--muted-foreground)]">{index + 1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{copy.title}</h3><p className="mt-1 max-w-xl text-sm leading-6 text-[var(--muted-foreground)]">{copy.description}</p></div><button type="button" role="switch" aria-checked={stage.enabled} aria-label={`${copy.title} enabled`} disabled={unavailable} onClick={onToggle} className="inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] px-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)] disabled:cursor-not-allowed disabled:opacity-50"><span className={`relative h-6 w-11 rounded-full ${stage.enabled ? "bg-[var(--primary)]" : "bg-[var(--border)]"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition-transform ${stage.enabled ? "translate-x-6" : "translate-x-1"}`} /></span><span>{stage.enabled ? "On" : "Off"}</span></button></div><div className="mt-3 flex flex-wrap items-end gap-4"><div className="min-w-56 flex-1"><label htmlFor={inputId} className="text-xs font-medium text-[var(--muted-foreground)]">{copy.title} · {copy.unit}</label><input id={inputId} type="range" min={stage.id === "loudness-normalization" ? -24 : 0} max={stage.id === "loudness-normalization" ? -9 : 100} step={stage.id === "loudness-normalization" ? 1 : 5} value={value} disabled={!stage.enabled || unavailable} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full accent-[var(--primary)] disabled:opacity-50" aria-valuetext={displayValue(stage)} /><output htmlFor={inputId} className="mt-1 block text-sm font-medium">{displayValue(stage)}</output></div><Button type="button" variant="ghost" size="sm" onClick={onReset}><RotateCcw className="size-4" aria-hidden="true" />Reset</Button></div>{capability.status !== "ready" && <p className="mt-3 text-xs leading-5 text-amber-200" role="status">{capability.message ?? (capability.status === "unavailable" ? "This stage needs a local speech capability before it can be enabled." : "CPU-safe fallback is active for this stage.")}</p>}</div></div></article>; }
