"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Download, FolderOpen } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { defaultProcessingProfile, outputProfileSchema, type OutputProfile, type ProcessingProfile } from "@/shared/contracts/processing";

function extensionFor(format: OutputProfile["format"]) { return format === "audio-wav" ? "wav" : format === "audio-flac" ? "flac" : format === "audio-mp3" ? "mp3" : format === "audio-m4a" ? "m4a" : "mp4"; }
function labelFor(format: OutputProfile["format"]) { return format === "audio-wav" ? "WAV · PCM 24-bit" : format === "audio-flac" ? "FLAC · lossless" : format === "audio-mp3" ? "MP3 · 192 kbps" : format === "audio-m4a" ? "M4A · AAC 192 kbps" : format === "source-video" ? "Source container · AAC 192 kbps" : "MP4 · H.264/AAC fallback"; }

type OutputProfileProps = { mediaRef: string; sourceName: string; sourceFormat: string; mediaKind: "audio" | "video"; selectedAudioStreamId?: string; targetExists?: boolean; targetName?: string; supportsSourceContainer?: boolean; fileSystemAccessAvailable?: boolean; onProfileChange?: (profile: ProcessingProfile) => void };

export function OutputProfilePanel({ mediaRef, sourceName, sourceFormat, mediaKind, selectedAudioStreamId, targetExists = false, targetName, supportsSourceContainer = true, fileSystemAccessAvailable = typeof window !== "undefined" && "showSaveFilePicker" in window, onProfileChange }: OutputProfileProps) {
  const initial = useMemo(() => { const profile = defaultProcessingProfile(mediaRef, selectedAudioStreamId, mediaKind, sourceFormat, targetName ?? (mediaKind === "video" ? "enhanced-output.mp4" : "enhanced-output.wav")); const fallback = mediaKind === "video" && !supportsSourceContainer && profile.output.format === "source-video"; const output = fallback ? { ...profile.output, format: "mp4" as const, audioCodec: "aac" as const, audioBitrateKbps: 192, videoCodec: "h264" as const, destination: { ...profile.output.destination, targetName: `${sourceName.replace(/\.[^.]+$/, "")}-enhanced.mp4` } } : profile.output; return { ...profile, output: { ...output, destination: { ...output.destination, mode: (fileSystemAccessAvailable ? "ask" : "browser-download") as OutputProfile["destination"]["mode"], targetName: targetName ?? output.destination.targetName, targetRef: targetName === sourceName ? "source" : `destination:${targetName ?? output.destination.targetName}`, exists: targetExists } } }; }, [fileSystemAccessAvailable, mediaKind, mediaRef, selectedAudioStreamId, sourceFormat, sourceName, supportsSourceContainer, targetExists, targetName]);
  const [profile, setProfile] = useState<ProcessingProfile>(initial);
  const output = profile.output;
  const validation = outputProfileSchema.safeParse(output);
  const errorMessage = validation.success ? "" : validation.error.issues[0]?.message ?? "Review the output settings.";
  const formatOptions = mediaKind === "audio" ? ["audio-wav", "audio-flac", "audio-mp3", "audio-m4a"] as const : ["source-video", "mp4"] as const;
  const setOutput = (next: OutputProfile) => { const nextProfile = { ...profile, output: next }; setProfile(nextProfile); onProfileChange?.(nextProfile); };
  const update = (changes: Partial<OutputProfile>) => setOutput({ ...output, ...changes });
  const changeFormat = (format: OutputProfile["format"]) => { const video = mediaKind === "video"; const target = `${sourceName.replace(/\.[^.]+$/, "")}-enhanced.${extensionFor(format)}`; update({ format, audioCodec: video ? "aac" : format === "audio-wav" ? "pcm_s24le" : format === "audio-flac" ? "flac" : format === "audio-m4a" ? "aac" : "mp3", audioBitrateKbps: video || ["audio-mp3", "audio-m4a"].includes(format) ? 192 : undefined, videoCodec: video ? (format === "source-video" ? "source" : "h264") : undefined, destination: { ...output.destination, targetName: target, targetRef: target === sourceName ? "source" : `destination:${target}`, exists: false, overwriteConfirmed: false } }); };
  const outputExecutionAvailable = mediaKind === "audio" && output.format === "audio-wav";
  const ready = validation.success && outputExecutionAvailable;

  return <section className="mt-8 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-raised)] p-5" aria-labelledby="output-profile-title"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--primary)]">Output profile</p><h2 id="output-profile-title" className="mt-1 text-xl font-semibold">Where should this go?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted-foreground)]">Choose an output destination. Only verified output paths can be marked ready.</p></div><Badge>{ready ? <><CheckCircle2 className="mr-1 size-3.5" aria-hidden="true" />Ready to review</> : <><AlertTriangle className="mr-1 size-3.5" aria-hidden="true" />Unavailable</>}</Badge></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-sm font-medium">Format and container</span><select aria-label="Output format" value={output.format} onChange={(event) => changeFormat(event.target.value as OutputProfile["format"])} className="mt-2 min-h-11 w-full rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]">{formatOptions.filter((format) => format !== "source-video" || supportsSourceContainer).map((format) => <option key={format} value={format} disabled={!(mediaKind === "audio" && format === "audio-wav")}>{labelFor(format)}{format === "audio-wav" || format === "source-video" || format === "mp4" ? "" : " · not available yet"}</option>)}</select></label><label className="block"><span className="text-sm font-medium">Quality <span className="text-xs text-[var(--muted-foreground)]">(not applied by verified output paths)</span></span><select aria-label="Output quality" value={output.quality} disabled className="mt-2 min-h-11 w-full rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"><option value="high">High detail</option><option value="standard">Standard size</option></select></label></div>
    <div className="mt-4 rounded-[var(--radius-md)] bg-[var(--surface-elevated)] p-4"><p className="text-sm font-medium">Encoding summary</p><p className="mt-1 text-sm leading-6 text-[var(--muted-foreground)]">{outputExecutionAvailable ? `48 kHz sample rate · ${labelFor(output.format)} · experimental WAV audio export` : mediaKind === "video" ? "Final video export is not implemented yet; no video stream will be encoded or replaced." : `${labelFor(output.format)} is not implemented yet. Only WAV audio output currently has a validated local processing path.`}</p></div>
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-sm font-medium">Destination</span><select aria-label="Output destination" value={output.destination.mode} onChange={(event) => update({ destination: { ...output.destination, mode: event.target.value as OutputProfile["destination"]["mode"] } })} className="mt-2 min-h-11 w-full rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]">{fileSystemAccessAvailable && <option value="ask">Choose a local folder when saving</option>}<option value="browser-download">Browser save/download</option></select></label><label className="block"><span className="text-sm font-medium">Output name</span><input aria-label="Output name" value={output.destination.targetName} onChange={(event) => { const next = event.target.value; update({ destination: { ...output.destination, targetName: next, targetRef: next === sourceName ? "source" : `destination:${next}` } }); }} className="mt-2 min-h-11 w-full rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]" /></label></div>
    <div className="mt-4 flex items-center gap-2 text-xs text-[var(--muted-foreground)]">{output.destination.mode === "browser-download" ? <Download className="size-4" aria-hidden="true" /> : <FolderOpen className="size-4" aria-hidden="true" />}<span>{fileSystemAccessAvailable && output.destination.mode === "ask" ? "The browser will ask for a local destination when saving." : "This file will remain on this device and use the browser save flow."}</span></div>
    {output.destination.exists && <div className="mt-4 rounded-[var(--radius-md)] border border-amber-300/40 bg-amber-300/10 p-4" role="alert"><p className="text-sm font-medium text-amber-100">This target already exists</p><p className="mt-1 text-sm leading-6 text-amber-100/80">{output.destination.targetName} will not be replaced unless you explicitly confirm overwrite.</p><label className="mt-3 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={output.destination.overwriteConfirmed} onChange={(event) => update({ destination: { ...output.destination, overwriteConfirmed: event.target.checked } })} className="size-4 accent-[var(--primary)]" /> Confirm overwrite for this target</label></div>}
    {errorMessage && <p className="mt-4 text-sm text-rose-200" role="alert">{errorMessage}</p>}
    <div className="mt-5 flex flex-wrap items-center gap-3"><Button type="button" disabled={!ready}>{outputExecutionAvailable ? "Output profile ready" : "Output path unavailable"}</Button><span className="text-xs text-[var(--muted-foreground)]">No file is written until a later processing step.</span></div>
  </section>;
}
